name: ciantis_basic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  file_picker: ^10.3.7
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CiantisSerif
      fonts:
        - asset: assets/fonts/Georgia.ttf
        - asset: assets/fonts/Georgia-Italic.ttf
          style: italic
    - family: CiantisVerse
      fonts:
        - asset: assets/fonts/Garamond.ttf
        - asset: assets/fonts/Garamond-Italic.ttf
          style: italic
